#!/usr/sbin/nft -f
# v3(2026-09-10 深夜):+8445-8454(多地区出口节点) ;其余同 v2
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        iif "lo" accept
        ct state established,related accept
        ct state invalid drop
        ip protocol icmp accept
        meta l4proto ipv6-icmp accept
        tcp dport 52913 accept
        tcp dport 443 accept
        udp dport 443 accept
        tcp dport 8388 accept
        tcp dport 8444 accept
        tcp dport 8445-8454 accept
        udp dport 20000-50000 accept
        tcp dport 2096 accept
    }
    chain forward { type filter hook forward priority filter; policy accept; }
    chain output  { type filter hook output priority filter; policy accept; }
}

table inet nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        udp dport 20000-50000 redirect to :443
    }
}
